# Generated by Django 4.2.7 on 2023-12-17 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('especialidades', '0004_pedidosexames'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacoteConsultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendado', models.BooleanField(default=True)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('E', 'Agendada'), ('F', 'Finalizada')], max_length=2)),
                ('resultado', models.FileField(blank=True, null=True, upload_to='resultados')),
                ('requer_senha', models.BooleanField(default=False)),
                ('senha', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('I', 'Cardiologista'), ('S', 'Urologista')], max_length=2)),
                ('preco', models.FloatField()),
                ('disponivel', models.BooleanField(default=True)),
                ('horario_inicial', models.IntegerField()),
                ('horario_final', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitacaoexame',
            name='exame',
        ),
        migrations.RemoveField(
            model_name='solicitacaoexame',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='PedidosExames',
        ),
        migrations.DeleteModel(
            name='SolicitacaoExame',
        ),
        migrations.DeleteModel(
            name='TipoExames',
        ),
        migrations.AddField(
            model_name='solicitacaoconsulta',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='especialidades.tipoconsulta'),
        ),
        migrations.AddField(
            model_name='solicitacaoconsulta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pacoteconsultas',
            name='especialidades',
            field=models.ManyToManyField(to='especialidades.solicitacaoconsulta'),
        ),
        migrations.AddField(
            model_name='pacoteconsultas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
