# Generated by Django 4.2.7 on 2023-12-17 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0005_pacoteconsultas_profissionais_solicitacaoconsulta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('A', 'Agendada'), ('F', 'Finalizada')], max_length=2)),
                ('preco', models.FloatField()),
                ('disponivel', models.BooleanField(default=True)),
                ('horario_inicial', models.IntegerField()),
                ('horario_final', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='solicitacaoconsulta',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='especialidades.statusconsulta'),
        ),
        migrations.DeleteModel(
            name='TipoConsulta',
        ),
    ]
