# Generated by Django 4.2.7 on 2023-12-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0006_statusconsulta_alter_solicitacaoconsulta_consulta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profissionais',
            name='ultimo_nome',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissionais',
            name='especialidades',
            field=models.ManyToManyField(to='especialidades.especialidades'),
        ),
    ]
