# Generated by Django 4.2.7 on 2023-12-17 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0007_especialidades_profissionais_ultimo_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoconsulta',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='solicitacaoconsulta',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='profissionais',
            name='especialidades',
        ),
        migrations.DeleteModel(
            name='PacoteConsultas',
        ),
        migrations.DeleteModel(
            name='SolicitacaoConsulta',
        ),
        migrations.DeleteModel(
            name='StatusConsulta',
        ),
        migrations.AddField(
            model_name='profissionais',
            name='especialidades',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='especialidades.especialidades'),
            preserve_default=False,
        ),
    ]
