# Generated by Django 4.2.7 on 2023-12-17 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0008_remove_solicitacaoconsulta_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionais',
            name='especialidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='especialidades.especialidades'),
        ),
    ]
