# Generated by Django 4.2.7 on 2023-12-17 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissionais',
            name='especialidades',
        ),
        migrations.CreateModel(
            name='ProfissionalEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='especialidades.especialidades')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='especialidades.profissionais')),
            ],
        ),
    ]
