# Generated by Django 4.2.7 on 2023-12-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0013_remove_profissionais_especialidades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissionalespecialidade',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='profissionalespecialidade',
            name='especialidade',
            field=models.ManyToManyField(to='especialidades.especialidades'),
        ),
    ]
