# Generated by Django 4.2.7 on 2023-12-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0015_especialidade_profissional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidades',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profissional__isnull': True}, related_name='profissionais', to='especialidades.especialidade'),
        ),
    ]
