# Generated by Django 4.2.7 on 2023-12-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0017_alter_profissional_especialidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='especialidades',
        ),
        migrations.DeleteModel(
            name='Especialidade',
        ),
        migrations.AddField(
            model_name='profissional',
            name='especialidades',
            field=models.CharField(choices=[('C', 'Cardiologista'), ('U', 'UROLOGISTA'), ('A', 'ANALOGISTA')], default=3, max_length=2),
            preserve_default=False,
        ),
    ]
