# Generated by Django 4.2.7 on 2023-12-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0018_remove_profissional_especialidades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='especialidades.especialidade'),
        ),
    ]
