# Generated by Django 4.2.7 on 2023-12-18 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('especialidades', '0019_especialidade_alter_profissional_especialidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='especialidades',
            new_name='especialidades',
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField()),
                ('Profissional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='especialidades.profissional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
