# Generated by Django 4.2.7 on 2023-12-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0021_rename_consultas_agendamentoconsulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='especialidades',
        ),
        migrations.DeleteModel(
            name='AgendamentoConsulta',
        ),
        migrations.DeleteModel(
            name='Profissional',
        ),
    ]
