# Generated by Django 4.2.7 on 2023-12-18 17:58

import cpf_field.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('especialidades', '0022_remove_profissional_especialidades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ultimo_nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('CPF', cpf_field.models.CPFField(max_length=14)),
                ('especialidades', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='especialidades.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField()),
                ('Profissional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='especialidades.profissional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
