# Generated by Django 4.2.7 on 2023-12-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_newuser_options_alter_newuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='CPF',
        ),
        migrations.AddField(
            model_name='newuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
